### ISSUE TITLE
Suggestion/Question regarding the update script

### ISSUE THREAD

**Issue by jrwrigh** [sourcethemes/academic-kickstart#78]
I've only recently noticed that the update script will update to the master branch of the theme instead an official release version. 

My suggestion/question would be that maybe the script should update the latest release tag instead. The "question" part is whether grabbing the master branch is the intended effect of the update script. I've seen a few issues now that are generally related to unknowingly using the master branch (and thus running into bugs) that probably could've been avoided by only upgrading on an official release.

See gcushen/hugo-academic/issues/614 and gcushen/hugo-academic/issues/1638 as examples of improper use of the master branch.

**Comment by gcushen** [comment]
See https://sourcethemes.com/academic/docs/update/ . The official recommended approach that is documented on the site is to upgrade to a specific version.

The purpose of the update script in the Kickstart repo is to display any new commits from the master branch and provide the option to install those commits. Its primary purpose is for the repo maintainers to use rather than site admins, although site admins may find it useful if they wish to use the bleeding edge version.

**Comment by jrwrigh** [comment]
Gotcha. Thanks for the clarification.

**Comment by jrwrigh** [comment]
It might be worth mentioning this clarification in the documentation. Looking back on it, [the info box](https://sourcethemes.com/academic/docs/update/#preparation) seems to suggest that the script is for official use rather being an alternative to the process detailed.
